[package]
name = "xcelmate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["serde_derive"] }
thiserror = "2.0.6"
zip = "2.2.0"
quick-xml = { version = "0.36.1" }
bimap = "0.6.3"
num_enum = "0.7.3"